version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "/media/pi/CRUST/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/media/pi/CRUST/images:/app/data/images" # CHANGE ME
      - "/media/pi/CRUST/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 80:80
    restart: always

volumes:
  db-data:
